# docker-compose.yml
version: '3.7'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9200:9200"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
