apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-processor
  template:
    metadata:
      labels:
        app: request-processor
    spec:
      containers:
        - name: request-processor
          image: request-processor:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: request-processor
spec:
  selector:
    app: request-processor
  ports:
    - port: 8080
      targetPort: 8080
